rootProject.name = 'rover'

pluginManagement {
    plugins {
        id 'org.gradle.toolchains.foojay-resolver-convention'  version '0.8.0'
    }
    repositories {
        maven {
            allowInsecureProtocol = true
            url = "http://nexus:8081/repository/maven-public/"
        }
    }
}