jpa.connection.url=jdbc:h2:file:./webapps/rover/WEB-INF/classes/data/rover-db
jpa.connection.username=sa
jpa.connection.password=sa
path.dir.photo=webapps/rover/WEB-INF/classes/photo
path.dir.data=webapps/rover/WEB-INF/classes/data
security.basic.username=${SECURITY_BASIC_USERNAME}
security.basic.password-hash=${SECURITY_BASIC_PASSWORD_HASH}